- hosts: localhost
  tasks:
    - debug:
        msg: play1
- name: Run user.yml
  import_playbook: user.yml
- name: Run kube-dependencies.yml
  import_playbook: kube-dependencies.yml
- name: Run init-first-master.yml
  import_playbook: init-first-master.yml
- name: Run init-other-master.yml
  import_playbook: init-other-master.yml
- name: Run worker.yml
  import_playbook: worker.yml
- name: Run monitoring.yml
  import_playbook: monitoring.yml
