- hosts: Master-01
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command
    - name: get certificate-key
      shell: kubeadm init phase upload-certs --upload-certs
      register: certs
    - name: register join command
      add_host: 
        name: "master_host"
        master_join_command: "{{ join_command.stdout }} --certificate-key {{ certs.stdout_lines[2]}}"
- hosts: Master-02, Master-03
  become: yes
  gather_facts: false
  tasks:
    - name: daemon-reload
      become: yes
      ansible.builtin.file:
        path: /etc/containerd/config.toml
        state: absent
    - name: Restart service httpd, in all cases
      ansible.builtin.service:
        name: containerd
        state: restarted
    - name: join cluster
      shell: "{{ hostvars['master_host']['master_join_command'] }} --control-plane >> master_joined.txt"
    
    - name: create .kube directory
      become: yes
      become_user: admin
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755
    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/admin/.kube/config
        remote_src: yes
        owner: admin