- hosts: master-01
  become: yes
  tasks:
    - name: Kubernetes namespace
      shell: kubectl create namespace monitoring
      become_user: admin
      args:
        chdir: /home/admin/Ansible-HA-Automation
    - name: Create cluster role
      shell: kubectl create -f clusterRole.yaml
      become_user: admin
      args:
        chdir: /home/admin/Ansible-HA-Automation
    - name: Create config-map
      shell: && kubectl create -f config-map.yaml
      become_user: admin
      args:
        chdir: /home/admin/Ansible-HA-Automation
    - name: Create Prometheus deployment
      shell: && kubectl create  -f prometheus-deployment.yaml 
      become_user: admin
      args:
        chdir: /home/admin/Ansible-HA-Automation
    - name: Create Prometheus service
      shell: kubectl create -f prometheus-service.yaml --namespace=monitoring
      become_user: admin
      args:
        chdir: /home/admin/Ansible-HA-Automation
    - name: Create grafana source
      shell: kubectl create -f grafana-datasource-config.yaml
      become_user: admin
      args:
        chdir: /home/admin/Ansible-HA-Automation
    - name: Create grafana deployment
      shell: kubectl create -f deployment.yaml
      become_user: admin
      args:
        chdir: /home/admin/Ansible-HA-Automation
    - name: Create grafana service
      shell: kubectl create -f service.yaml
      become_user: admin
      args:
        chdir: /home/admin/Ansible-HA-Automation




    
    

    
  