- hosts: masters
  become: yes
  vars:
    password: student
  tasks:
    - name: create the admin user
      user: name=admin append=yes state=present createhome=yes shell=/bin/bash password="{{password | password_hash('sha512')}}"
    - name: give admin passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: 'admin ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Update apt
      apt: update_cache =yes force_apt_get=yes cache_vaild_time=3600

    - name: Upgrade package
      apt: upgrade=dist force_apt_get=yes

    - name: Install ACL
      apt: 
        name: acl
        state: latest

    - name: Reboot indien nodig
      reboot:
        msg: "Reboot voor update"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists