- hosts: masters
  become: yes
  vars:
    password: student
  tasks:
    - name: create the admin user
      user: name=admin append=yes state=present createhome=yes shell=/bin/bash password="{{password | password_hash('sha512')}}"
    - name: give admin passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: 'admin ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'