- hosts: master-01
  become: yes

  tasks:
    - name: Create Prometheus namespace
      shell: kubectl create namespace prometheus
      become_user: admin
    
    - name: Add Helm GPG key 1
      shell: curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null 
      args:
        warn: false

    - name: Intall Transport 
      apt:
        name: apt-transport-https
      
    - name: Add Helm GPG key 2
      shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
      
    - name: Install helm  
      apt:
        update_cache: yes
        name: helm

    - name: Add Prometheus Stack repo
      shell: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts && helm repo update
      become_user: admin

    - name: Install Prometheus Stack 
      shell: helm install prometheus prometheus-community/kube-prometheus-stack --namespace prometheus
      become_user: admin

    - name: Delete Service
      shell: kubectl delete service prometheus-grafana -n prometheus
      become_user: admin

    - name: Expose Grafana Dashboard
      shell: kubectl expose deployment prometheus-grafana --type=NodePort --name=prometheus-grafana -n prometheus
      become_user: admin

    - name: Install Kubernetes Dashboard
      shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.5.0/aio/deploy/recommended.yaml
      become_user: admin

    - name: Kubedashbord Admin Account
      shell: kubectl -n kubernetes-dashboard create serviceaccount dashboard-admin
      become_user: admin

    - name: Kubedashbord Role Binding
      shell: kubectl -n kubernetes-dashboard create clusterrolebinding dashboard-admin --clusterrole=cluster-admin --serviceaccount=default:dashboard-admin-sa
      become_user: admin

    - name: Expose Kubernetes Dashboard
      shell: kubectl delete service kubernetes-dashboard -n kubernetes-dashboard && kubectl expose deployment kubernetes-dashboard --type=NodePort --name=kubernetes-dashboard -n kubernetes-dashboard
      become_user: admin

    - name: Kubernetes Dashboard Token
      shell: kubectl -n kubernetes-dashboard create token dashboard-admin
      register: token_output
      become_user: admin

    - name: Requesting Grafana Port
      shell: kubectl -n prometheus get service prometheus-grafana
      register: grafana_port
      become_user: admin

    - name: Requesting Dashboard Port
      shell: kubectl -n kubernetes-dashboard get service kubernetes-dashboard
      register: dashboard_port
      become_user: admin

    - name: Install Kubescape
      shell: curl -s https://raw.githubusercontent.com/armosec/kubescape/master/install.sh | /bin/bash
      args:
        warn: false

    - name: Write info to /tmp/important.txt
      copy:
        dest: "/tmp/important.txt"
        content: |
          "{{ token_output.stdout }}"
          "{{dashboard_port.stdout}}"
          "{{grafana_port.stdout}}"
          "Grafna login = admin:prom-operator"
      delegate_to: localhost

    - name: Post install message
      debug:
        msg:
          - 'Things left to do:'
          - '- Info about Kuberneets-dashboard & Grafana can be found in /tmp/important.txt !!!!Put this file somewhere secure!!!!'
          - '- Kubescape can be used on master-01: kubescape scan --submit --enable-host-scan --verbose'
          - '- Have fun - Jasper & Kubilay'